name: Github Container Registry Package Cleaner
on:
  workflow_dispatch:
    inputs:
      versionstokeep:
        type: string
        required: true
        default: '5'
      package:
        type: string
        required: true

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Deleting all but ${{ inputs.versionstokeep }} from ${{ inputs.package }}
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ inputs.package }}
          package-type: container
          min-versions-to-keep: ${{ inputs.versionstokeep }}
